spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 3772
  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: create
          open-in-view: false

loan:
  minimalIncome: 40000
  minCarValue: 1000000